// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: lifecycle.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginLifecycle_Init_FullMethodName  = "/sdk.v1.PluginLifecycle/Init"
	PluginLifecycle_Start_FullMethodName = "/sdk.v1.PluginLifecycle/Start"
	PluginLifecycle_Stop_FullMethodName  = "/sdk.v1.PluginLifecycle/Stop"
)

// PluginLifecycleClient is the client API for PluginLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginLifecycle defines the gRPC service for plugin lifecycle management.
// Plugins implement this service to integrate with the ML-Elec core.
type PluginLifecycleClient interface {
	// Init initializes the plugin with the provided configuration.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// Start starts the plugin. Called after successful Init.
	Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error)
	// Stop gracefully stops the plugin.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type pluginLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginLifecycleClient(cc grpc.ClientConnInterface) PluginLifecycleClient {
	return &pluginLifecycleClient{cc}
}

func (c *pluginLifecycleClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) Start(ctx context.Context, in *StartRequest, opts ...grpc.CallOption) (*StartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginLifecycleServer is the server API for PluginLifecycle service.
// All implementations must embed UnimplementedPluginLifecycleServer
// for forward compatibility.
//
// PluginLifecycle defines the gRPC service for plugin lifecycle management.
// Plugins implement this service to integrate with the ML-Elec core.
type PluginLifecycleServer interface {
	// Init initializes the plugin with the provided configuration.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// Start starts the plugin. Called after successful Init.
	Start(context.Context, *StartRequest) (*StartResponse, error)
	// Stop gracefully stops the plugin.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedPluginLifecycleServer()
}

// UnimplementedPluginLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginLifecycleServer struct{}

func (UnimplementedPluginLifecycleServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedPluginLifecycleServer) Start(context.Context, *StartRequest) (*StartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedPluginLifecycleServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPluginLifecycleServer) mustEmbedUnimplementedPluginLifecycleServer() {}
func (UnimplementedPluginLifecycleServer) testEmbeddedByValue()                         {}

// UnsafePluginLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginLifecycleServer will
// result in compilation errors.
type UnsafePluginLifecycleServer interface {
	mustEmbedUnimplementedPluginLifecycleServer()
}

func RegisterPluginLifecycleServer(s grpc.ServiceRegistrar, srv PluginLifecycleServer) {
	// If the following call panics, it indicates UnimplementedPluginLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginLifecycle_ServiceDesc, srv)
}

func _PluginLifecycle_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).Start(ctx, req.(*StartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginLifecycle_ServiceDesc is the grpc.ServiceDesc for PluginLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sdk.v1.PluginLifecycle",
	HandlerType: (*PluginLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _PluginLifecycle_Init_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _PluginLifecycle_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PluginLifecycle_Stop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lifecycle.proto",
}
