// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"ml-elec/internal/api"
	"ml-elec/internal/config"
	"ml-elec/internal/nats"
	"ml-elec/internal/plugin"
	"ml-elec/internal/storage"
)

// Injectors from wire.go:

// InitializeApp wires all components together using Google Wire.
func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	natsConfig := ProvideNATSConfig(configConfig)
	server, err := nats.New(natsConfig)
	if err != nil {
		return nil, err
	}
	storageConfig := ProvideStorageConfig(configConfig)
	store, err := storage.New(storageConfig)
	if err != nil {
		return nil, err
	}
	manager := plugin.NewManager()
	apiConfig := ProvideAPIConfig(configConfig)
	apiServer := api.NewServer(apiConfig, store)
	app := &App{
		Config:     configConfig,
		NATSServer: server,
		Store:      store,
		PluginMgr:  manager,
		APIServer:  apiServer,
	}
	return app, nil
}

// wire.go:

// ProvideNATSConfig extracts NATS config from the main config.
func ProvideNATSConfig(cfg *config.Config) *config.NATSConfig {
	return &cfg.NATS
}

// ProvideStorageConfig extracts storage config from the main config.
func ProvideStorageConfig(cfg *config.Config) *config.StorageConfig {
	return &cfg.Storage
}

// ProvideAPIConfig extracts API config from the main config.
func ProvideAPIConfig(cfg *config.Config) *config.APIConfig {
	return &cfg.API
}

// App holds all application components wired together.
type App struct {
	Config     *config.Config
	NATSServer *nats.Server
	Store      *storage.Store
	PluginMgr  *plugin.Manager
	APIServer  *api.Server
}
